# Generated by Django 5.2.7 on 2025-11-25 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinginquiry',
            name='booking_reference',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='bookinginquiry',
            name='package',
            field=models.CharField(choices=[('basic', 'Basic Package - $1,500'), ('premium', 'Premium Package - $2,500'), ('vip', 'VIP Package - $3,500+')], default='basic', max_length=20),
        ),
        migrations.AddField(
            model_name='bookinginquiry',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=1500.0, max_digits=8),
        ),
        migrations.AddField(
            model_name='bookinginquiry',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='bookinginquiry',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
    ]
