# Generated by Django 5.2.3 on 2025-11-28 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_bookinginquiry_booking_reference_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewsArticle',
        ),
    ]
